# Generated by Django 5.2 on 2025-06-05 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id_turista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='cargos')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reservacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('destino', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('logo', models.FileField(blank=True, null=True, upload_to='cargos')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='Reservacion.turista')),
            ],
        ),
    ]
